DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL UNIQUE,
  body VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  post_id INT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  body VARCHAR(250) NOT NULL
);

ALTER TABLE comments
    ADD FOREIGN KEY (post_id)
    REFERENCES posts(id);
